apiVersion: v1
kind: Service
metadata:
  labels:
    app: server-kube
  name: server-service
  namespace: default
spec:
  type: NodePort
  ports:
    - nodePort: 30011
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    component: server
##  type: LoadBalancer
##status:
##  loadBalancer: {}
